# 此处规则是large的时候HPA会最多比预配的pod数多8个，非large的则多2个
{{- if eq .Values.prodType "prod" }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.replicaCount }}
  {{- if eq .Values.deploymentType  "large" }}
  maxReplicas: {{ add .Values.replicaCount 8 }}
  {{- else }}
  maxReplicas: {{ add .Values.replicaCount 2 }}
  {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 40
{{- end }}