apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.prodType }}-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.hostSuffix }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.prodType }}-svc
            port:
              number: 80
        pathType: Prefix
        path: /
# {{- if eq (index .Values.ingress.annotations "kubernetes.io/ingress.class" ) [[外网的ingress]]" }}
#   {{- toYaml .Values.tlsConfig | nindent 2 }}
# {{- end }}
# {{- if eq .Values.prodType "yfb" }}
#     {{- toYaml .Values.tlsConfig | nindent 2 }}
# {{- end }}